### ISSUE TITLE
Error in URL on documentation page

### ISSUE THREAD

**Issue by kylecaulfield** [Azure-Samples/iot-hub-node-intel-edison-getstartedkit#5]
In this page you have an error on your wget urls:

https://azure.microsoft.com/en-us/documentation/samples/iot-hub-node-intel-edison-getstartedkit/

2.9 Modify Device Sample
In your Edison boards command line, type the following command to transfer the files to your board:
wget hhttps://raw.githubusercontent.com/Azure-Samples/iot-hub-node-intel-edison-getstartedkit/blob/master/command_center/command_center.js

The correct URL is https://raw.githubusercontent.com/Azure-Samples/iot-hub-node-intel-edison-getstartedkit/master/command_center/command_center.js

please note both hhttp is incorrect and no /blob/

**Comment by kylecaulfield** [comment]
Same page, just below you have 

Open the file remote_monitoring.js in a text editor using the command:
vi remote_monitoring.js

This should be 
vi command_center.js

**Comment by hegate** [comment]
Hi @kylecaulfield thanks for pointing it out. We'll take care of it right away. Thanks, H.
