### ISSUE TITLE
wget URLs appear incorrect.  

### ISSUE THREAD

**Issue by BretStateham** [Azure-Samples/iot-hub-node-intel-edison-getstartedkit#6]
In section 2.9, the "wget https://...." urls for the command_center.js and package.json files appear incorrect for me, I had to use the urls without the /blob/ path included. These wget statements worked for me:

```
wget https://raw.githubusercontent.com/Azure-Samples/iot-hub-node-intel-edison-getstartedkit/master/command_center/command_center.js
wget https://raw.githubusercontent.com/Azure-Samples/iot-hub-node-intel-edison-getstartedkit/master/command_center/package.json
```

**Comment by hegate** [comment]
Thanks @BretStateham , we have updated the tutorial.
