### ISSUE TITLE
bower install like

### ISSUE THREAD

**Issue by SocalSam** [Azure-Samples/iot-hub-node-intel-edison-getstartedkit#8]
In the section: https://github.com/Azure-Samples/iot-hub-node-intel-edison-getstartedkit#28-node-application-setup, 

The line:
bower install
throws 'bower' is not recognized as an internal or external command.

**Comment by AttunixCorp** [comment]
Hello SocalSam -

When installing Node, did you make sure to select the options to install NPM and add to it to your PATH? Additionally, do you get the same error when you type it in (as opposed to a copy and paste)?
